### ISSUE TITLE
Generating a Crossplane Provider document should be updated.

### ISSUE THREAD

**Issue by rimbi** [upbound/upjet#174] opened 2023-03-15 08:56 UTC
### What happened?
I have tried to start developing a crossplane openstack provider using the guide [here](https://github.com/upbound/upjet/blob/main/docs/generating-a-provider.md). I had an issue in the test phase.  When I `make run` at step 5, I get the following error: 
```
config/provider.go:24:12: pattern provider-metadata.yaml: no matching files found
```
This `provider-metadata.yaml` file which exists in `provider-aws` is neither present in the template repository nor is it mentioned in the guide.

### How can we reproduce it?
Just follow the guide and you'll encounter the issue at 5th step in the test phase.

**Comment by svscheg** [comment] 2023-03-16 18:47
Hi @rimbi , using setup documentation  https://github.com/upbound/upjet/blob/main/docs/generating-a-provider.md I could not reproduce the issue. 

`make run` command working without error. All configuration was done using provided configuration step by step for GitHub, file provider-metadata.yaml is present


![Image](https://user-images.githubusercontent.com/114226153/225720497-5ce212fa-c77f-4b0b-ba81-26e742501786.png)

Could you please add more details like: which provider you try to create, also please re-check - does provider-metadata.yaml is present after you clone repository in step 2 on the **Generate** section?

**Comment by rimbi** [comment] 2023-03-17 05:39
Hi @svscheg ,

You are right. The problem is that I have been doing all of these on my mac, which is probably not supported and not mentioned in the guide. After trying it on a linux I do not see the problem.

If my inference about mac is right, it should be stated in the guide.

Thanks.

**Comment by svscheg** [comment] 2023-05-11 11:55
Hi @rimbi , I tested it on Mac OS Ventura and it is ok. Could you try it once again and if this issue is not reproducible we can close the issue.

**Comment by turkenf** [comment] 2023-07-24 13:03
Hi @rimbi, We have updated the Generating a Crossplane Provider document, could you please try again and let us know if you run into any issues?

**Comment by jeanduplessis** [comment] 2023-10-10 11:54
I'm closing this issue. If the problem still persist feel free to add a comment again.

**Closed by jeanduplessis** 2023-10-10 11:54 UTC
Labels: bug, needs:triage, needs:information
